[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    titleHome = "Genocs Library"
    titleAddition = "Documentation for .NET libraries, CLI, and templates"
    description = "Documentation for Genocs Library—NuGet packages, CLI, and templates for cloud-ready .NET microservices."
    footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

[it]
  languageName = "Italiano"
  contentDir = "content/it"
  weight = 20
  [it.params]
    languageISO = "IT"
    titleHome = "Documentazione Genocs Framework"
    titleAddition = "La Documentazione per l'utilizzo del framework per lo sviluppo di Soluzioni Enterprise"
    description = "La Documentazione Genocs Framework è un set completo di informazioni che contiene Librerie, Best Practice, per sviluppare software moderna, sicuro, scalabile, velocemente."
    footer = "Alimentato da <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, e <a href=\"https://getdoks.org/\">Doks</a>"
