# This is a manually triggered dockerhub build and publish

name: Publish to Dockerhub

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Image Version"

        # Default value if no value is explicitly provided
        default: "1.0.0"

        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Log in
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to Dockerhub
        run: |
          docker build -f Dockerfile -t genocs/genocs-library:${{ github.event.inputs.version }} -t genocs/genocs-library:latest .
          docker push genocs/genocs-library:${{ github.event.inputs.version }}
          docker push genocs/genocs-library:latest
