name: github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Delete temporary directories
        run: npm run clean
      - name: Build production website
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GT_TOKEN }}
          publish_dir: ./public
          cname: blog.genocs.com
